name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: Tagged release
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Verify this is an annotated tag
        run: |
          if [ -z "$GITHUB_REF" ]; then
            echo "ERROR: GITHUB_REF is empty or not defined" >&2
            exit 1
          fi

          # See https://github.com/actions/checkout/issues/290
          git fetch origin +$GITHUB_REF:$GITHUB_REF

          tag_type=$(git cat-file -t "$GITHUB_REF")
          if [ "$tag_type" != "tag" ]; then
            echo "ERROR: This action should only run for annotated tags" >&2
            exit 1
          fi

      - name: Create cache directory
        run: |
          mkdir -p ~/cache

      - name: Activate cache
        uses: actions/cache@v2
        with:
          path: ~/cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/go.sum') }}

      - name: Run pre-commit
        run: >
          docker run --rm
          -v ~/cache:/cache
          -e XDG_CACHE_HOME=/cache
          -e GOCACHE=/cache/go-build
          -e GOMODCACHE=/cache/go-mod
          -e PRE_COMMIT_HOME=/cache/pre-commit
          -e HOME=/build/src
          -v $PWD:/build/src
          -w /build/src
          -u $UID
          quay.io/larsks/opf-pre-commit:0b40f89 pre-commit run --all-files

      - name: Build
        run: >
          docker run --rm
          -v ~/cache:/cache
          -e XDG_CACHE_HOME=/cache
          -e GOCACHE=/cache/go-build
          -e GOMODCACHE=/cache/go-mod
          -e PRE_COMMIT_HOME=/cache/pre-commit
          -e HOME=/build/src
          -v $PWD:/build/src
          -w /build/src
          -u $UID
          quay.io/larsks/opf-pre-commit:0b40f89 make release

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: opfcli-*-*
          token: ${{ secrets.GITHUB_TOKEN }}
