name: Container test
on:
  workflow_dispatch: {}

jobs:
  docker-test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/larsks/opf-pre-commit:0b40f89
      env:
        XDG_CACHE_HOME: /cache
        GOCACHE: /cache/go-build
        GOMODCACHE: /cache/go-mod
        PRE_COMMIT_HOME: /cache/pre-commit
      volumes:
        - /cache
    steps:
      - uses: actions/checkout@v2

      - name: Activate cache
        uses: actions/cache@v2
        with:
          path: /cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/go.sum') }}

      - name: Run pre-commit checks
        run: pre-commit run --all-files

      - name: Check cache
        run: |
          find /cache -type f -print | head -40
